import React from 'react'
import type {Metadata} from "next";
import {Providers} from './global-redux/providers'

import {Inter} from "next/font/google";
import './assets/globals.css'
import {Room} from "@/app/Room";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Providers>
      <Room>
        {children}
      </Room>
    </Providers>
    </body>
    </html>
  );
}
